### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by yuaner90** [KorfLab/StochHMM#11]
Hi,
   when I use this software for DRIP peak calling, I encounter an issue, could you tell me an easy way to fix it ?

**Comment by lottpaul** [comment]
Sorry, without additional information I can't even start to troubleshoot
the issues.   Please provide additional information (System, model,
command-line, ....).

Can you recreate the issue on an established system with a model and
minimal datasets?  That can be shared for troubleshooting.

If you cant, the best I can do is say - turn around three times and try
again...

**Comment by fangyuan900709** [comment]
sure, I cam list my command-line, actually it's the DRIPc software which required stochhmm.  
 https://github.com/chedinlab/DRIPc/tree/master/peak_calling/DRIPc 
stochhmm -seq DR_CX_all.normalized.customfa  -model  DRIPc.hmm  -posterior -threshold 0.9 -gff > peaks.txt

**Comment by lottpaul** [comment]
Unfortunately, I wasn't the one that developed the DRIPc.hmm file and don't have access to it.   Your best bet is to contact the person who created it.
