### ISSUE TITLE
Error while compiling

### ISSUE THREAD

**Issue by shokoohi** [KorfLab/StochHMM#14]
./stochMath.h:139:18: error: call to 'abs' is ambiguous
            base=abs(base);
                 ^~~
lexicalTable.cpp:470:16: note: in instantiation of function template
      specialization 'StochHMM::integerPower<unsigned long>' requested here
                        array_size*=integerPower(alpha_size, (size_t) or...
                                    ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include/stdlib.h:137:6: note: 
      candidate function
int      abs(int) __pure2;
         ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/stdlib.h:115:44: note: 
      candidate function
inline _LIBCPP_INLINE_VISIBILITY long      abs(     long __x) _NOEXCEPT ...
                                           ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/stdlib.h:117:44: note: 
      candidate function
inline _LIBCPP_INLINE_VISIBILITY long long abs(long long __x) _NOEXCEPT ...
                                           ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/math.h:693:1: note: 
      candidate function
abs(float __lcpp_x) _NOEXCEPT {return ::fabsf(__lcpp_x);}
^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/math.h:697:1: note: 
      candidate function
abs(double __lcpp_x) _NOEXCEPT {return ::fabs(__lcpp_x);}
^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/math.h:701:1: note: 
      candidate function
abs(long double __lcpp_x) _NOEXCEPT {return ::fabsl(__lcpp_x);}
^
1 error generated.
make[2]: *** [lexicalTable.o] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

**Comment by lottpaul** [comment]
Thanks.    Resolved it.

Line 139:  
+base=std::abs((int)base);
to
-base=abs(base);
