### ISSUE TITLE
Use std::ostream for outputs

### ISSUE THREAD

**Issue by plata** [KorfLab/StochHMM#8]
std::ostream should be used for outputs. It might be initialized with std::cout/cerr.
The current solution of printing directly to std::cout/cerr makes it very inconvenient to use StochHMM as a library because error messages cannot be logged correctly.

**Comment by lottpaul** [comment]
Thanks for the critique.  Do you have a reference to a coding standard, so that we can make sure that the code is compliant?

**Comment by plata** [comment]
I did not find a coding standard regarding this. But I think what would be best to do is:
* Error handling in case of errors (e.g. if there is a mistake in the hmm file) → exceptions inside the library, std::cerr only in the command line part (=main), thereby separating library and user interface

* Logging facility in case of debug/notification messages. This can be done in a generic way. See http://www.drdobbs.com/cpp/logging-in-c/201804215?pgno=1 (especially page 3). However, I would not recommend to introduce a boost dependency. But the concept should become clear.
