### ISSUE TITLE
Installing on Microsoft Windows 10

### ISSUE THREAD

**Issue by myahia1972** [KorfLab/StochHMM#9]
Hello.
It may not the proper place to post this issue, but unfortunately, I don't know where to post it. Regarding the installation on windows 10, how to create the executable files using **_nmake_**. I have already installed and run MS VCVARS32. But I couldn't find the makefie (.mkf) in the StochHMM directory

**Comment by lottpaul** [comment]
Currently StochHMM relies on the GNU GCC not the Visual C++.   I believe it was the Gamma function in the statistics code.   Ultimately, it needs to be switched to depend on BOOST, but for now you're best bet is to use GNU GCC.  In the past, I've used MinGW to compile for Windows Machines
